name: idee
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sqflite: any
  sqflite_common_ffi: ^2.3.3
  sqlite3: ^2.4.2
  sqlite3_flutter_libs: ^0.5.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.0.7
  image_picker: ^0.8.4+4
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
